# Generated by Django 5.2.5 on 2025-11-29 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
