# Generated by Django 5.2.5 on 2025-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
